name: NuGet publish

on:
  release:
    types: [published]

jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      # Publish
      - name: Create nupkg
        run: dotnet pack --include-symbols -c Release -o ./pkg -p:PackageVersion=${{ github.event.release.tag_name }}

      - name: NuGetPush
        run: dotnet nuget push "pkg/*.nupkg" -k ${{secrets.NUGET_PUBLISH_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate
